### ISSUE TITLE
from_distribution behaviour with rand 0.6

### ISSUE THREAD

**Issue by nbrr** [rustsim/nalgebra#528]
The following code compiles with `rand 0.5`

```Rust
use rand::prelude::*;
use rand::distributions::StandardNormal;

let mut rng = rand::thread_rng();
let dist = StandardNormal;
let x : DVector<f64> = DVector::<f64>::from_distribution(4,&dist,&mut rng);
println!("{:}",x);
```

but raises an error with `rand 0.6`

```
error[E0277]: the trait bound `rand::distributions::normal::StandardNormal: rand::distributions::Distribution<f64>` is not satisfied
     let x : DVector<f64> = DVector::<f64>::from_distribution(4,&dist,&mut rng);
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `rand::distributions::Distribution<f64>` is not implemented for `rand::distributions::normal::StandardNormal`
   = note: required by `nalgebra::base::construction::<impl nalgebra::base::matrix::Matrix<N, nalgebra::base::dimension::Dynamic, C, <nalgebra::base::default_allocator::DefaultAllocator as nalgebra::base::allocator::Allocator<N, nalgebra::base::dimension::Dynamic, C>>::Buffer>>::from_distribution`
```

Other use of `Distribution<f64>` trait seem to work on `rand 0.6` so I imagine the problem comes from nalgebra:
```Rust
fn f<D: Distribution<f64>, R: Rng>(dist: D, r: &mut R) -> f64 {
    dist.sample(r)
}
let mut rng = rand::thread_rng();
let v = f(StandardNormal, &mut rng);
println!("{}",v);
```

**Comment by Ralith** [comment]
I don't think rand 0.6 is supported by any currently-released version of nalgebra.

**Comment by dhardy** [comment]
nalgebra supports rand 0.6 since version 0.17 (Feb 3rd).

Unfortunately impls are specific to the version of the crate used, so you must use the same version of `rand` (unless a compatibility shim exists — but we've had enough issues with these for `rand_core` that adding them for `rand` too does not seem favourable).

I don't think there's anything to be done here (except possibly documentation).
